### ISSUE TITLE
Zprovoznit content building na Windows

### ISSUE THREAD

**Issue by RisaI** [RisaI/mff-totem#34]
Je potreba napsat a otestovat skripty na buildeni contentu na Windows platforme. Na Linuxu pouzivame na buildeni XNA veci MonoGame Content Pipeline (mgcb.exe), na buildeni shaderu pouzivame fxb.exe z DirectX SDK (to by bylo dobre pouzivat i na Windowsu).

**Comment by m93a** [comment]
Dokud se nevyřeší issue thoemmi/7Zip4Powershell#47, nebude fungovat automatické rozbalování knihoven.
