### ISSUE TITLE
Přidat podporu Unicode v konzoli

### ISSUE THREAD

**Issue by m93a** [RisaI/mff-totem#37]
Konzole má na Windowsech problémy s Unicodem – na konci každého řádku a místo písmen s diakritikou jsou otazníky.

![image](https://user-images.githubusercontent.com/1671665/36357482-da969d12-14fe-11e8-8f26-c1144826e645.png)

**Comment by RisaI** [comment]
Diakritiku pridas pridanim Character regionu do Content/fonts/console.spritefont (na konci souboru). Muzes zjistit, co za char zpusobuje otaznik na konci?

**Comment by m93a** [comment]
Konzole je implementovaná jako redirect `System.Console` a ta automaticky používá EOL podle platformy – pro Unix `\n`, pro Windows `\r\n`. Vyřešil jsem to tak, že se `\r` při vypisování prostě ignoruje. Platformy, na kterých se nový řádek značí jenom `\r`, stejně nerozjedou dotnet.
